// Placeholder types - will be auto-generated by ts-rs from Rust backend
// Run: npm run type-gen to generate these from Rust

export interface User {
  id: number;
  email: string;
  nombre: string;
  apellidos: string;
  rut: string;
  telefono?: string;
  region_id?: number;
  user_type: string;
  status: string;
  email_verified: boolean;
  created_at: string;
  updated_at: string;
}

export interface AuthResponse {
  user: User;
  token: string;
  expires_at: string;
}

export interface Job {
  id: number;
  company_id: number;
  category_id?: number;
  region_id?: number;
  title: string;
  description: string;
  requirements?: string;
  benefits?: string;
  salary_min?: number;
  salary_max?: number;
  salary_currency?: string;
  employment_type?: string;
  vacancies: number;
  application_deadline?: string;
  status: string;
  views_count: number;
  created_at: string;
  updated_at: string;
  published_at?: string;
}

export interface JobWithCompany extends Job {
  company_name: string;
  company_logo?: string;
  category_name?: string;
  region_name?: string;
}

export interface JobListResponse {
  jobs: JobWithCompany[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
}

export interface JobApplication {
  id: number;
  job_id: number;
  user_id: number;
  cover_letter?: string;
  cv_url?: string;
  status: string;
  applied_at: string;
  reviewed_at?: string;
}
